name: smart_arb_translator
description: An intelligent command-line utility for translating ARB files with Google Translate API, featuring smart change detection and modular architecture.
version: 1.3.3
repository: https://github.com/FredrikBorgstrom/smart_arb_translator.git
homepage: https://github.com/FredrikBorgstrom/smart_arb_translator
documentation: https://github.com/FredrikBorgstrom/smart_arb_translator#readme

environment:
  sdk: ">=3.0.1 <4.0.0"

executables:
  smart_arb_translator: translate

dependencies:
  arb_merge: ^1.2.2
  args: ^2.7.0
  collection: ^1.19.1
  console: ^4.1.0
  html_unescape: ^2.0.0
  http: ^1.4.0
  intl_utils: ^2.8.10
  path: ^1.9.1
  petitparser: ^6.1.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2

smart_arb_translator:
  source_arb: test.arb
  dart_main_locale: en
  api_key: api_key.txt
  cache_directory: cache
  l10n_directory: output
  l10n_method: none
  generate_dart: false